<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="10" hostname="EN310366" failures="0" tests="9" name="Login Tests" time="246.604" errors="0" timestamp="2023-02-10T10:38:26 CET">
  <testcase classname="tests.login.SuccessfulLoginLogout" name="@BeforeMethod setupTest" time="29.588">
    <failure type="java.lang.AssertionError" message="Wrong Response Status Code in postUser(successloginlogout230210103436) Api Call! Response Body: {&amp;quot;timestamp&amp;quot;:1676021684827,&amp;quot;status&amp;quot;:500,&amp;quot;error&amp;quot;:&amp;quot;Internal Server Error&amp;quot;,&amp;quot;exception&amp;quot;:&amp;quot;java.lang.IllegalArgumentException&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Incorrect format of About!&amp;quot;,&amp;quot;path&amp;quot;:&amp;quot;/api/users/add&amp;quot;} expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: Wrong Response Status Code in postUser(successloginlogout230210103436) Api Call! Response Body: {"timestamp":1676021684827,"status":500,"error":"Internal Server Error","exception":"java.lang.IllegalArgumentException","message":"Incorrect format of About!","path":"/api/users/add"} expected [200] but found [500]
at utils.RestApiUtils.postUser(RestApiUtils.java:130)
at utils.RestApiUtils.postUser(RestApiUtils.java:135)
at tests.login.SuccessfulLoginLogout.setupTest(SuccessfulLoginLogout.java:62)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setupTest -->
  <testcase classname="tests.practice.Tooltip" name="@BeforeMethod setUpTest" time="29.588">
    <failure type="java.lang.AssertionError" message="Wrong Response Status Code in postUser(uselesstooltip230210103436) Api Call! Response Body: {&amp;quot;timestamp&amp;quot;:1676021684827,&amp;quot;status&amp;quot;:500,&amp;quot;error&amp;quot;:&amp;quot;Internal Server Error&amp;quot;,&amp;quot;exception&amp;quot;:&amp;quot;java.lang.IllegalArgumentException&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Incorrect format of About!&amp;quot;,&amp;quot;path&amp;quot;:&amp;quot;/api/users/add&amp;quot;} expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: Wrong Response Status Code in postUser(uselesstooltip230210103436) Api Call! Response Body: {"timestamp":1676021684827,"status":500,"error":"Internal Server Error","exception":"java.lang.IllegalArgumentException","message":"Incorrect format of About!","path":"/api/users/add"} expected [200] but found [500]
at utils.RestApiUtils.postUser(RestApiUtils.java:130)
at utils.RestApiUtils.postUser(RestApiUtils.java:135)
at tests.practice.Tooltip.setUpTest(Tooltip.java:39)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUpTest -->
  <testcase classname="tests.heroes.DeleteHero" name="@BeforeMethod setupTest" time="29.696">
    <failure type="java.lang.AssertionError" message="Wrong Response Status Code in postUser(addnewhero230210103436) Api Call! Response Body: {&amp;quot;timestamp&amp;quot;:1676021684962,&amp;quot;status&amp;quot;:500,&amp;quot;error&amp;quot;:&amp;quot;Internal Server Error&amp;quot;,&amp;quot;exception&amp;quot;:&amp;quot;org.springframework.dao.IncorrectResultSizeDataAccessException&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements&amp;quot;,&amp;quot;path&amp;quot;:&amp;quot;/api/users/add&amp;quot;} expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: Wrong Response Status Code in postUser(addnewhero230210103436) Api Call! Response Body: {"timestamp":1676021684962,"status":500,"error":"Internal Server Error","exception":"org.springframework.dao.IncorrectResultSizeDataAccessException","message":"result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements","path":"/api/users/add"} expected [200] but found [500]
at utils.RestApiUtils.postUser(RestApiUtils.java:130)
at utils.RestApiUtils.postUser(RestApiUtils.java:135)
at tests.heroes.DeleteHero.setupTest(DeleteHero.java:51)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setupTest -->
  <testcase classname="tests.heroes.AddNewHero" name="@BeforeMethod setupTest" time="29.7">
    <failure type="java.lang.AssertionError" message="Wrong Response Status Code in postUser(addnewhero230210103436) Api Call! Response Body: {&amp;quot;timestamp&amp;quot;:1676021684962,&amp;quot;status&amp;quot;:500,&amp;quot;error&amp;quot;:&amp;quot;Internal Server Error&amp;quot;,&amp;quot;exception&amp;quot;:&amp;quot;org.springframework.dao.IncorrectResultSizeDataAccessException&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements&amp;quot;,&amp;quot;path&amp;quot;:&amp;quot;/api/users/add&amp;quot;} expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: Wrong Response Status Code in postUser(addnewhero230210103436) Api Call! Response Body: {"timestamp":1676021684962,"status":500,"error":"Internal Server Error","exception":"org.springframework.dao.IncorrectResultSizeDataAccessException","message":"result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements","path":"/api/users/add"} expected [200] but found [500]
at utils.RestApiUtils.postUser(RestApiUtils.java:130)
at utils.RestApiUtils.postUser(RestApiUtils.java:135)
at tests.heroes.AddNewHero.setupTest(AddNewHero.java:53)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setupTest -->
  <testcase classname="tests.practice.Tooltip" name="testUselessTooltip" time="0.0">
    <skipped/>
  </testcase> <!-- testUselessTooltip -->
  <testcase classname="tests.login.SuccessfulLoginLogout" name="JIRA00001E" time="0.0">
    <skipped/>
  </testcase> <!-- JIRA00001E -->
  <testcase classname="tests.heroes.DeleteHero" name="testDeleteHero" time="0.0">
    <skipped/>
  </testcase> <!-- testDeleteHero -->
  <testcase classname="tests.heroes.AddNewHero" name="testAddNewHero" time="0.0">
    <skipped/>
  </testcase> <!-- testAddNewHero -->
  <testcase classname="tests.login.UnsuccessfulLoginWrongPassword" name="testUnsuccessfulLoginWrongPassword" time="20.723"/>
  <testcase classname="tests.users.VerifyUserDetails" name="testVerifyUserDetails" time="46.774"/>
  <testcase classname="tests.register.SuccessfulRegister" name="testRegisterNewUser" time="59.271"/>
  <testcase classname="tests.users.AddNewUserTest" name="testAddingNewUser" time="79.589"/>
  <testcase classname="tests.practice.VerifyDragAndDrop" name="testDragAndDrop" time="197.126"/>
  <testcase classname="tests.profile.VerifyProfileImage" name="testVerifyProfileImage" time="0.0">
    <ignored/>
  </testcase> <!-- testVerifyProfileImage -->
  <testcase classname="tests.api.VerifyErrorPostAlreadyExistingUser" name="testVerifyErrorPostAlreadyExistingUser" time="0.0">
    <ignored/>
  </testcase> <!-- testVerifyErrorPostAlreadyExistingUser -->
  <testcase classname="tests.login.DemoTest" name="testDemoTest" time="0.0">
    <ignored/>
  </testcase> <!-- testDemoTest -->
  <testcase classname="tests.api.VerifyErrorGetNonExistingUser" name="testApiForNonExistingUser" time="0.0">
    <ignored/>
  </testcase> <!-- testApiForNonExistingUser -->
  <testcase classname="tests.page_evaluation.EvaluateLoginPage" name="testEvaluateLoginPageLocators" time="0.0">
    <ignored/>
  </testcase> <!-- testEvaluateLoginPageLocators -->
  <testcase classname="tests.login.LoginTest" name="testUnsuccessfulLoginWrongPassword" time="0.0">
    <ignored/>
  </testcase> <!-- testUnsuccessfulLoginWrongPassword -->
  <testcase classname="tests.api.VerifyErrorGetUserNoPermission" name="testVerifyErrorGetUserNoPermission" time="0.0">
    <ignored/>
  </testcase> <!-- testVerifyErrorGetUserNoPermission -->
  <testcase classname="tests.api.VerifyErrorPostUserNoEmail" name="testVerifyErrorPostUserNoEmail" time="0.0">
    <ignored/>
  </testcase> <!-- testVerifyErrorPostUserNoEmail -->
  <testcase classname="tests.login.LoginTest" name="testSuccessfulLoginLogout" time="0.0">
    <ignored/>
  </testcase> <!-- testSuccessfulLoginLogout -->
  <testcase classname="tests.database.DatabaseTest" name="testApiForNonExistingUser" time="0.0">
    <ignored/>
  </testcase> <!-- testApiForNonExistingUser -->
</testsuite> <!-- Login Tests -->
